---
#Install mariadb via ansible create database

- name: Install MYSQL
  yum:
    name: mariadb-server #debian: mysql-server
    state: present

- name: Install MySQL python, this package is required to remove the anonymous user
  yum: name=http://mirror.centos.org/centos/7/os/x86_64/Packages/MySQL-python-1.2.5-1.el7.x86_64.rpm state=present

- name: Install the Python MySQL Support Libraries
  yum: pkg={{item}} state=latest
  with_items:
    - mariadb

- name: start mysql server and enable it on reboot
  service: name=mariadb state=started enabled=true #debian: mysql

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy the root credentials as .my.cnf file
  template: src=my.cnf.j2 dest=~/.my.cnf mode=0600

- name: firewalld rule to add mysql port 3306
  firewalld:
    port: "{{ mysql_port }}"
    permanent: true
    state: enabled
    immediate: yes
  notify: restart firewalld

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present


