---
# This playbook will install mysql and create db user and give permissions.

- name: Install MySQL 5.7 repo
  yum: name=http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm state=present

- name: Install MySQL python, this package is required to remove the anonymous user 
  yum: name=http://mirror.centos.org/centos/7/os/x86_64/Packages/MySQL-python-1.2.5-1.el7.x86_64.rpm state=present

- name: Install MySQL Server
  yum: name=mysql-server state=present

- name: Install MySQL python, this package is required to remove the anonymous user
  yum: name={{item}} state=latest
  with_items:
    - python-mysqldb 

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

- name: Remove test database if it exist.
  mysql_db: name=test state=absent

- name: Remove all anonymous user accounts
  mysql_user: name='' host_all=yes state=absent

- name: Change root password
  mysql_user: name=root host={{item}} password={{upassword}}
  with_items:
    - "{{ansible_hostname}}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: sestatus.rc != 0

- name: firewalld rule to add mysql port 3306
  firewalld:
    port: "{{ mysql_port }}"
    permanent: true
    state: enabled
    immediate: yes  
  notify: restart firewalld

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
